version: "3.6"

services:
  public_odc:
    image: postgres:11.5-alpine
    ports:
      - "5436:5432"
    environment:
      - POSTGRES_DB=public-odc
      - POSTGRES_PASSWORD=opendatacubepassword
      - POSTGRES_USER=public-odc
    expose:
      - 5432
    restart: always

  dea_intertidal:
    build:
      context: .
      args:
        - ENVIRONMENT=dev
    environment:
      - ODC_DB_HOSTNAME=public_odc
      - ODC_DB_USERNAME=public-odc
      - ODC_DB_PASSWORD=opendatacubepassword
      - ODC_DB_DATABASE=public-odc
      - AWS_DEFAULT_REGION=ap-southeast-2
      - AWS_ACCESS_KEY_ID=fake_id
      - AWS_SECRET_ACCESS_KEY=fake_key
      - AWS_NO_SIGN_REQUEST=YES
      - SQLALCHEMY_SILENCE_UBER_WARNING=1
      - GDAL_HTTP_MAX_RETRY=10
    volumes:
      - .:/code
      - ./tide_models/:/var/share/tide_models
      - ./artifacts:/mnt/artifacts
    depends_on:
      - public_odc
    command: ["/bin/sh", "-ec", "while :; do echo '.'; sleep 180 ; done"]

  public_index:
     image: opendatacube/datacube-index:latest
     environment:
        - DB_HOSTNAME=public_odc
        - DB_USERNAME=public-odc
        - DB_PASSWORD=opendatacubepassword
        - DB_DATABASE=public-odc
        - DB_PORT=5432
        - AWS_DEFAULT_REGION=ap-southeast-2
        - SQLALCHEMY_SILENCE_UBER_WARNING=1
     depends_on:
        - public_odc
     entrypoint: bash -c 'sleep infinity'
