Virtual product:
    virtual_product_path: configs/dea_virtual_product_landsat_s2.yaml
Input files:
    grid_path: https://dea-public-data.s3.ap-southeast-2.amazonaws.com/derivative/dea_coastlines/supplementary/ga_summary_grid_c3_32km_coastal.geojson
